

  // Si tienes un archivo global CSS
import '../styles/estilos.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        {/* Vincula el archivo CSS */}
        <link rel="stylesheet" href="/c:\Users\Uuario\Desktop\PIFA\styles\tablaindicadores.module.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}